-- =====================================================================
--  Library System — Oracle SQL Schema (Two-App build)
--  Target: Oracle Database XE 11.2+ (works on 18c/21c XE as well)
--  Shared by both the public Reader site and the private Admin app,
--  but each app reaches it through a different, separated API layer.
-- =====================================================================

-- ---------------------------------------------------------------------
--  STAFF — library staff accounts. role = ADMIN (full) | FRONT_DESK.
--  added_by_staff_id records which admin created the account.
-- ---------------------------------------------------------------------
CREATE TABLE staff (
    staff_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR2(120)      NOT NULL,
    email             VARCHAR2(160)      NOT NULL,
    password_hash     VARCHAR2(255)      NOT NULL,
    role              VARCHAR2(20)  DEFAULT 'FRONT_DESK' NOT NULL,
    is_active         CHAR(1)       DEFAULT 'Y' NOT NULL,
    added_on          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    added_by_staff_id NUMBER,
    CONSTRAINT uq_staff_email UNIQUE (email),
    CONSTRAINT ck_staff_role  CHECK (role IN ('ADMIN','FRONT_DESK')),
    CONSTRAINT ck_staff_active CHECK (is_active IN ('Y','N')),
    CONSTRAINT fk_staff_addedby FOREIGN KEY (added_by_staff_id) REFERENCES staff(staff_id)
);

-- ---------------------------------------------------------------------
--  MEMBERS — readers / library members. A member MAY have an online
--  self-service account (password_hash set) for wishlist / notify-me,
--  and MAY have a staff-managed membership (status + expiry + fees).
--  membership_status: PENDING (self-signup, not yet a paid member),
--  ACTIVE, EXPIRED, SUSPENDED.
-- ---------------------------------------------------------------------
CREATE TABLE members (
    member_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR2(120)      NOT NULL,
    email             VARCHAR2(160)      NOT NULL,
    phone             VARCHAR2(40),
    password_hash     VARCHAR2(255),                 -- NULL = walk-in, no online login
    membership_status VARCHAR2(20)  DEFAULT 'PENDING' NOT NULL,
    membership_start  DATE,
    membership_expiry DATE,
    joined_on         TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_members_email UNIQUE (email),
    CONSTRAINT ck_members_status CHECK (membership_status IN
        ('PENDING','ACTIVE','EXPIRED','SUSPENDED'))
);

-- ---------------------------------------------------------------------
--  BOOKS — the catalog. status kept in sync with available_copies.
-- ---------------------------------------------------------------------
CREATE TABLE books (
    book_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR2(300)     NOT NULL,
    author           VARCHAR2(200)     NOT NULL,
    isbn             VARCHAR2(20),
    genre            VARCHAR2(80),
    description      CLOB,
    cover_image_url  VARCHAR2(500),
    shelf_location   VARCHAR2(60),
    total_copies     NUMBER(6)   DEFAULT 1 NOT NULL,
    available_copies NUMBER(6)   DEFAULT 1 NOT NULL,
    status           VARCHAR2(20) DEFAULT 'AVAILABLE' NOT NULL,
    search_count     NUMBER(10)  DEFAULT 0 NOT NULL,
    added_on         TIMESTAMP   DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_books_isbn   UNIQUE (isbn),
    CONSTRAINT ck_books_status CHECK (status IN ('AVAILABLE','CHECKED_OUT')),
    CONSTRAINT ck_books_copies CHECK (available_copies >= 0
                                      AND available_copies <= total_copies)
);

CREATE INDEX ix_books_genre  ON books (genre);
CREATE INDEX ix_books_status ON books (status);
CREATE INDEX ix_books_title_lower  ON books (LOWER(title));
CREATE INDEX ix_books_author_lower ON books (LOWER(author));

CREATE OR REPLACE TRIGGER trg_books_status
BEFORE INSERT OR UPDATE OF available_copies ON books
FOR EACH ROW
BEGIN
    IF :NEW.available_copies > 0 THEN
        :NEW.status := 'AVAILABLE';
    ELSE
        :NEW.status := 'CHECKED_OUT';
    END IF;
END;
/

-- ---------------------------------------------------------------------
--  BORROW_LOG — physical issue/return recorded by staff at the desk.
--  fine_amount accrues for overdue/damaged returns.
-- ---------------------------------------------------------------------
CREATE TABLE borrow_log (
    log_id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id              NUMBER NOT NULL,
    member_id            NUMBER,
    issued_on            TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    due_on               TIMESTAMP,
    returned_on          TIMESTAMP,
    fine_amount          NUMBER(10,2) DEFAULT 0 NOT NULL,
    handled_by_staff_id  NUMBER NOT NULL,
    CONSTRAINT fk_log_book   FOREIGN KEY (book_id)   REFERENCES books(book_id),
    CONSTRAINT fk_log_member FOREIGN KEY (member_id) REFERENCES members(member_id),
    CONSTRAINT fk_log_staff  FOREIGN KEY (handled_by_staff_id) REFERENCES staff(staff_id)
);

CREATE INDEX ix_log_book   ON borrow_log (book_id);
CREATE INDEX ix_log_member ON borrow_log (member_id);
CREATE INDEX ix_log_open   ON borrow_log (returned_on);

-- ---------------------------------------------------------------------
--  INVOICES — membership fees, fines, or other paid services.
-- ---------------------------------------------------------------------
CREATE TABLE invoices (
    invoice_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id             NUMBER NOT NULL,
    type                  VARCHAR2(20) NOT NULL,   -- MEMBERSHIP_FEE | FINE | OTHER
    amount                NUMBER(10,2) NOT NULL,
    issued_on             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    payment_status        VARCHAR2(20) DEFAULT 'UNPAID' NOT NULL,  -- UNPAID | PAID
    notes                 VARCHAR2(400),
    generated_by_staff_id NUMBER NOT NULL,
    CONSTRAINT fk_inv_member FOREIGN KEY (member_id) REFERENCES members(member_id),
    CONSTRAINT fk_inv_staff  FOREIGN KEY (generated_by_staff_id) REFERENCES staff(staff_id),
    CONSTRAINT ck_inv_type   CHECK (type IN ('MEMBERSHIP_FEE','FINE','OTHER')),
    CONSTRAINT ck_inv_status CHECK (payment_status IN ('UNPAID','PAID'))
);

CREATE INDEX ix_inv_member ON invoices (member_id);
CREATE INDEX ix_inv_status ON invoices (payment_status);

-- ---------------------------------------------------------------------
--  MAINTENANCE_RECORDS — damaged/lost book write-offs AND general
--  library upkeep. Either book_id (book-related) or asset_name
--  (general item) identifies the subject; both may be null for misc.
-- ---------------------------------------------------------------------
CREATE TABLE maintenance_records (
    record_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id             NUMBER,                 -- nullable: set for book issues
    asset_name          VARCHAR2(160),          -- nullable: set for general items
    category            VARCHAR2(30) DEFAULT 'OTHER' NOT NULL, -- BOOK_DAMAGE|BOOK_LOST|EQUIPMENT|FACILITY|OTHER
    description         VARCHAR2(600) NOT NULL,
    cost                NUMBER(10,2) DEFAULT 0 NOT NULL,
    logged_on           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    logged_by_staff_id  NUMBER NOT NULL,
    CONSTRAINT fk_maint_book  FOREIGN KEY (book_id) REFERENCES books(book_id),
    CONSTRAINT fk_maint_staff FOREIGN KEY (logged_by_staff_id) REFERENCES staff(staff_id),
    CONSTRAINT ck_maint_cat   CHECK (category IN
        ('BOOK_DAMAGE','BOOK_LOST','EQUIPMENT','FACILITY','OTHER'))
);

-- ---------------------------------------------------------------------
--  WISHLIST + NOTIFY_REQUESTS — reader-account features (tied to member).
-- ---------------------------------------------------------------------
CREATE TABLE wishlist (
    member_id  NUMBER NOT NULL,
    book_id    NUMBER NOT NULL,
    added_on   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_wishlist PRIMARY KEY (member_id, book_id),
    CONSTRAINT fk_wish_member FOREIGN KEY (member_id) REFERENCES members(member_id),
    CONSTRAINT fk_wish_book   FOREIGN KEY (book_id)   REFERENCES books(book_id)
);

CREATE TABLE notify_requests (
    request_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id       NUMBER NOT NULL,
    member_id     NUMBER NOT NULL,
    requested_on  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    notified_on   TIMESTAMP,
    CONSTRAINT fk_notify_book   FOREIGN KEY (book_id)   REFERENCES books(book_id),
    CONSTRAINT fk_notify_member FOREIGN KEY (member_id) REFERENCES members(member_id),
    CONSTRAINT uq_notify_open   UNIQUE (book_id, member_id)
);

-- ---------------------------------------------------------------------
--  AUDIT_LOG — who changed what and when (admin app accountability).
-- ---------------------------------------------------------------------
CREATE TABLE audit_log (
    audit_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id    NUMBER,
    action      VARCHAR2(40) NOT NULL,     -- CREATE | UPDATE | DELETE | LOGIN | ISSUE | RETURN ...
    entity      VARCHAR2(40) NOT NULL,     -- BOOK | MEMBER | INVOICE | STAFF ...
    entity_id   VARCHAR2(40),
    details     VARCHAR2(600),
    at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_audit_staff FOREIGN KEY (staff_id) REFERENCES staff(staff_id)
);

CREATE INDEX ix_audit_at ON audit_log (at);

COMMIT;
