import { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { api } from '../api/client.js';
import { useToast } from '../context/ToastContext.jsx';
import Pill from '../components/Pill.jsx';
import { money, date } from '../utils/format.js';

// Printable receipt. Uses the browser's print dialog (Save as PDF works).
export default function InvoiceDetail() {
  const { id } = useParams();
  const toast = useToast();
  const [inv, setInv] = useState(null);

  useEffect(() => { api.getInvoice(id).then((d) => setInv(d.invoice)).catch((e) => toast.error(e.message)); }, [id]); // eslint-disable-line
  if (!inv) return <p className="text-ink-400">Loading…</p>;

  return (
    <div className="max-w-2xl">
      <div className="flex items-center justify-between print:hidden">
        <Link to="/invoices" className="text-sm text-ink-500 hover:text-ink-900">← Invoices</Link>
        <button onClick={() => window.print()} className="btn-primary">Print / Save PDF</button>
      </div>

      <div className="card mt-4 p-8 print:border-0 print:shadow-none">
        <div className="flex items-start justify-between border-b border-ink-200 pb-6">
          <div>
            <p className="text-lg font-semibold text-ink-900">The Reading Room</p>
            <p className="mt-1 text-xs text-ink-500">14 Lamplight Lane, Fort District, Mumbai 400001</p>
            <p className="text-xs text-ink-500">hello@readingroom.test · +91 22 4000 0000</p>
          </div>
          <div className="text-right">
            <p className="text-sm font-semibold uppercase tracking-wide text-ink-900">Receipt</p>
            <p className="mt-1 font-mono text-xs text-ink-500">#{String(inv.invoice_id).padStart(5, '0')}</p>
            <p className="text-xs text-ink-500">{date(inv.issued_on)}</p>
          </div>
        </div>

        <div className="grid grid-cols-2 gap-6 py-6">
          <div>
            <p className="text-[11px] uppercase tracking-wide text-ink-400">Billed to</p>
            <p className="mt-1 text-ink-900">{inv.member_name}</p>
            {inv.member_email && <p className="text-sm text-ink-500">{inv.member_email}</p>}
          </div>
          <div className="text-right">
            <p className="text-[11px] uppercase tracking-wide text-ink-400">Status</p>
            <div className="mt-1 flex justify-end"><Pill value={inv.payment_status} /></div>
          </div>
        </div>

        <table className="w-full border-t border-ink-200 text-sm">
          <thead>
            <tr className="text-left text-[11px] uppercase tracking-wide text-ink-400">
              <th className="py-2">Description</th><th className="py-2 text-right">Amount</th>
            </tr>
          </thead>
          <tbody>
            <tr className="border-t border-ink-100">
              <td className="py-3 text-ink-800">
                {inv.type.replace(/_/g, ' ').toLowerCase()}
                {inv.notes && <span className="block text-xs text-ink-400">{inv.notes}</span>}
              </td>
              <td className="py-3 text-right tabular-nums text-ink-900">{money(inv.amount)}</td>
            </tr>
          </tbody>
          <tfoot>
            <tr className="border-t border-ink-200">
              <td className="py-3 font-semibold text-ink-900">Total</td>
              <td className="py-3 text-right text-lg font-semibold tabular-nums text-ink-900">{money(inv.amount)}</td>
            </tr>
          </tfoot>
        </table>

        <p className="mt-8 border-t border-ink-100 pt-4 text-center text-xs text-ink-400">
          Generated by {inv.generated_by || 'staff'} · Thank you for supporting your local library.
        </p>
      </div>
    </div>
  );
}
